import codelabRoutes from './codelab.routes.js';
import projectRoutes from './project.routes.js';
import interviewRoutes from './interview.routes.js';
import careerRoutes from './career.routes.js';
import gamificationRoutes from './gamification.routes.js';
import jobRoutes from './job.routes.js';
import aiCareerRoutes from './aiCareer.routes.js';
import { Router } from 'express';
import authRoutes from './auth.routes.js';
import courseRoutes from './course.routes.js';
import categoryRoutes from './category.routes.js';
import teacherRoutes from './teacher.routes.js';
import cartRoutes from './cart.routes.js';
import wishlistRoutes from './wishlist.routes.js';
import orderRoutes from './order.routes.js';
import paymentRoutes from './payment.routes.js';
import enrollmentRoutes from './enrollment.routes.js';
import progressRoutes from './progress.routes.js';
import reviewRoutes from './review.routes.js';
import couponRoutes from './coupon.routes.js';
import notificationRoutes from './notification.routes.js';
import certificateRoutes from './certificate.routes.js';
import adminRoutes from './admin.routes.js';
import supportRoutes from './support.routes.js';
import learningPathRoutes from './learningPath.routes.js';
import aptitudeRoutes from './aptitude.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/courses', courseRoutes);
router.use('/learning-paths', learningPathRoutes);
router.use('/aptitude', aptitudeRoutes);
router.use('/categories', categoryRoutes);
router.use('/teachers', teacherRoutes);
router.use('/cart', cartRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/progress', progressRoutes);
router.use('/reviews', reviewRoutes);
router.use('/coupons', couponRoutes);
router.use('/notifications', notificationRoutes);
router.use('/certificates', certificateRoutes);
router.use('/admin', adminRoutes);
router.use('/support', supportRoutes);

router.use('/codelab', codelabRoutes);
router.use('/projects', projectRoutes);
router.use('/interview', interviewRoutes);
router.use('/career', careerRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/jobs', jobRoutes);
router.use('/ai-career', aiCareerRoutes);

export default router;
