-- Migration 036: Complete Seed Course Catalog
-- Inserts 38 comprehensive courses matching all 22+ categories and full search terms into public.courses.


INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'react'), (SELECT id FROM public.categories LIMIT 1)),
    'Complete React JS Development',
    'complete-react-js-development',
    'Master modern React 19, Hooks, Redux Toolkit, React Router, and build 10+ production web apps.',
    'Comprehensive journey from foundational JavaScript to building high-performance, accessible React applications. You will learn JSX, state, props, custom hooks, context API, Redux Toolkit, SSR basics, performance tuning, and deploy full applications.',
    'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1600&auto=format&fit=crop&q=80',
    89.99,
    19.99,
    'beginner',
    2310,
    94210,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['React', 'JavaScript', 'Frontend', 'Web Development', 'Hooks', 'Redux']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'react'), (SELECT id FROM public.categories LIMIT 1)),
    'Advanced React and TypeScript',
    'advanced-react-and-typescript',
    'Enterprise scalable React architecture with strict TypeScript, generic components, and micro-frontends.',
    'Level up your React engineering with TypeScript. Learn how to type custom hooks, build reusable polymorphic component libraries, handle complex discriminated union states, and optimize rendering performance.',
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1600&auto=format&fit=crop&q=80',
    109.99,
    24.99,
    'advanced',
    1680,
    48300,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['React', 'TypeScript', 'Frontend', 'Enterprise', 'Architecture']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'react'), (SELECT id FROM public.categories LIMIT 1)),
    'React Projects for Beginners',
    'react-projects-for-beginners',
    'Learn React by building 5 practical interactive projects: E-Commerce, Weather App, Quiz, and Dashboard.',
    'The fastest way to learn React is by building actual web apps. No dry theoretical lectures: code along from minute one to build five complete, portfolio-ready projects with Tailwind CSS and React.',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1600&auto=format&fit=crop&q=80',
    0,
    0,
    'beginner',
    720,
    112000,
    4.8,
    'published',
    'free',
    ARRAY[]::TEXT[],
    ARRAY['React', 'JavaScript', 'Beginner', 'Projects', 'Free']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'python'), (SELECT id FROM public.categories LIMIT 1)),
    'Python Programming for Beginners',
    'python-programming-for-beginners',
    'Go from zero to building real scripts, automation tools, and web scrapers with Python 3.',
    'Master Python from the absolute basics to writing clean, idiomatic code. Learn variables, data structures, loops, functions, object-oriented programming (OOP), file I/O, error handling, and web scraping with BeautifulSoup.',
    'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=1600&auto=format&fit=crop&q=80',
    79.99,
    16.99,
    'beginner',
    1920,
    87400,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Python', 'Programming', 'Automation', 'Beginner', 'Coding']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'python'), (SELECT id FROM public.categories LIMIT 1)),
    'Advanced Python Programming',
    'advanced-python-programming',
    'Metaprogramming, decorators, async/await concurrency, generators, and high-performance design patterns.',
    'Take your Python skills to senior level. Dive deep into Python internals, memory management, generators, context managers, custom decorators, multithreading, multiprocessing, and asyncio high-concurrency systems.',
    'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1600&auto=format&fit=crop&q=80',
    99.99,
    22.99,
    'advanced',
    1440,
    34100,
    4.9,
    'published',
    'premium',
    ARRAY[]::TEXT[],
    ARRAY['Python', 'AsyncIO', 'Concurrency', 'Advanced', 'Backend']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'data-science'), (SELECT id FROM public.categories LIMIT 1)),
    'Python for Data Science',
    'python-for-data-science',
    'Data analysis, manipulation, and visualization with NumPy, Pandas, Matplotlib, and Seaborn.',
    'Learn how to clean, analyze, and visualize complex datasets with the essential Python data science stack. Work with real-world financial, medical, and e-commerce datasets to uncover actionable insights.',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&auto=format&fit=crop&q=80',
    89.99,
    18.99,
    'intermediate',
    2160,
    68900,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Python', 'Data Science', 'Pandas', 'NumPy', 'Analytics', 'Data Visualization']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'java'), (SELECT id FROM public.categories LIMIT 1)),
    'Complete Java Programming',
    'complete-java-programming',
    'Master Java 21, Object-Oriented Design, Collections Framework, Multithreading, and Lambdas.',
    'Comprehensive course on modern Java from ground up. Learn syntax, data types, control flow, object-oriented design patterns, generics, streams API, and core software engineering practices.',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1600&auto=format&fit=crop&q=80',
    84.99,
    17.99,
    'beginner',
    2520,
    76500,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Java', 'OOP', 'Backend', 'Collections', 'Streams', 'Programming']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'java'), (SELECT id FROM public.categories LIMIT 1)),
    'Advanced Java Development',
    'advanced-java-development',
    'Spring Boot 3, Microservices, Hibernate / JPA, Kafka messaging, and Docker deployment.',
    'Take your Java skills into enterprise backend engineering. Build production RESTful microservices with Spring Boot, secure them with Spring Security and OAuth2, use Kafka event streaming, and deploy with Docker.',
    'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1600&auto=format&fit=crop&q=80',
    119.99,
    29.99,
    'advanced',
    2100,
    39200,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Java', 'Spring Boot', 'Microservices', 'Kafka', 'Backend', 'Docker']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'backend-development'), (SELECT id FROM public.categories LIMIT 1)),
    'Complete Node.js Backend Development',
    'complete-nodejs-backend-development',
    'Build scalable REST APIs, GraphQL services, authentication, and database integrations with Node.js.',
    'Comprehensive guide to server-side JavaScript with Node.js. Master asynchronous programming, event loop mechanics, Express.js architecture, MongoDB, PostgreSQL, JWT authentication, caching with Redis, and automated testing.',
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1600&auto=format&fit=crop&q=80',
    89.99,
    19.99,
    'intermediate',
    2040,
    71800,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Node.js', 'Express', 'Backend', 'JavaScript', 'REST API', 'Database']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'backend-development'), (SELECT id FROM public.categories LIMIT 1)),
    'Node.js and Express Masterclass',
    'nodejs-and-express-masterclass',
    'Advanced backend architecture, clean code principles, rate limiting, and microservices in Node.js.',
    'Deep-dive into professional backend architecture. Learn domain-driven design, repository patterns, middleware optimization, file streaming, rate limiting, and security best practices for high-traffic Node.js services.',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600&auto=format&fit=crop&q=80',
    94.99,
    21.99,
    'advanced',
    1560,
    31200,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Node.js', 'Express', 'Microservices', 'Architecture', 'Backend']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'full-stack'), (SELECT id FROM public.categories LIMIT 1)),
    'Full Stack Web Development',
    'full-stack-web-development',
    'HTML, CSS, JavaScript, React, Node.js, Express, PostgreSQL, and AWS full stack engineering.',
    'Become an elite full stack software engineer. Build real-world client-server architectures from the ground up: frontend interfaces in React, backend REST APIs in Express, persistent databases in PostgreSQL, and automated deployment.',
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1600&auto=format&fit=crop&q=80',
    129.99,
    29.99,
    'all_levels',
    3480,
    142000,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Full Stack', 'React', 'Node.js', 'PostgreSQL', 'JavaScript', 'Web Development']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'full-stack'), (SELECT id FROM public.categories LIMIT 1)),
    'MERN Stack Development',
    'mern-stack-development',
    'MongoDB, Express, React, and Node.js: Build full-stack social media and e-commerce platforms.',
    'Master the world''s most popular full-stack JavaScript ecosystem. Build full MERN applications from scratch with JWT auth, image uploads, real-time messaging with WebSockets, and payment gateways.',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1600&auto=format&fit=crop&q=80',
    99.99,
    19.99,
    'intermediate',
    2640,
    63400,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Full Stack', 'MERN', 'React', 'Node.js', 'MongoDB', 'Express']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'frontend-development'), (SELECT id FROM public.categories LIMIT 1)),
    'HTML CSS JavaScript Complete Course',
    'html-css-javascript-complete-course',
    'The foundational web development course. Master semantic HTML5, modern CSS Grid/Flexbox, and ES6+ JS.',
    'Start your web development journey right here. Master semantic markup, responsive design principles with Flexbox and Grid, CSS animations, and vanilla JavaScript DOM manipulation.',
    'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1600&auto=format&fit=crop&q=80',
    0,
    0,
    'beginner',
    1200,
    185000,
    4.9,
    'published',
    'free',
    ARRAY[]::TEXT[],
    ARRAY['HTML', 'CSS', 'JavaScript', 'Frontend', 'Beginner', 'Free']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'frontend-development'), (SELECT id FROM public.categories LIMIT 1)),
    'Advanced JavaScript',
    'advanced-javascript',
    'Closures, prototypal inheritance, Event Loop, Memory management, Web Workers, and design patterns.',
    'Deep dive under the hood of the V8 engine and the ECMAScript specification. Understand closures, lexical scoping, call-stack execution contexts, event loop microtasks vs macrotasks, and functional programming.',
    'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=1600&auto=format&fit=crop&q=80',
    79.99,
    17.99,
    'advanced',
    1080,
    42100,
    4.9,
    'published',
    'premium',
    ARRAY[]::TEXT[],
    ARRAY['JavaScript', 'Frontend', 'Advanced', 'V8 Engine', 'Closures']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'data-science'), (SELECT id FROM public.categories LIMIT 1)),
    'Data Science Masterclass',
    'data-science-masterclass',
    'Complete data science pathway: Statistical modeling, hypothesis testing, SQL, and predictive analytics.',
    'Master data science workflows from end to end. Formulate business hypotheses, extract data with SQL, clean messy real-world datasets, perform exploratory data analysis, and train predictive models.',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&auto=format&fit=crop&q=80',
    109.99,
    24.99,
    'intermediate',
    2400,
    52400,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Data Science', 'Python', 'SQL', 'Statistics', 'Machine Learning']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'backend-development'), (SELECT id FROM public.categories LIMIT 1)),
    'SQL and Database Development',
    'sql-and-database-development',
    'Master PostgreSQL and MySQL: Complex joins, window functions, indexing, optimization, and transactions.',
    'SQL is the universal language of data. Learn relational database design, normalization, multi-table joins, subqueries, common table expressions (CTEs), window functions, query execution plans, and performance index tuning.',
    'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=1600&auto=format&fit=crop&q=80',
    69.99,
    14.99,
    'all_levels',
    1320,
    67800,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['SQL', 'PostgreSQL', 'Database', 'Backend', 'Analytics']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'machine-learning'), (SELECT id FROM public.categories LIMIT 1)),
    'Machine Learning Fundamentals',
    'machine-learning-fundamentals',
    'Supervised & unsupervised algorithms: Linear regression, decision trees, random forests, and k-means.',
    'Understand the theory and code behind fundamental machine learning algorithms. Use Python and Scikit-Learn to build classification and regression models, evaluate performance with cross-validation, and avoid overfitting.',
    'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1600&auto=format&fit=crop&q=80',
    89.99,
    19.99,
    'beginner',
    1800,
    61200,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Machine Learning', 'Python', 'Scikit-Learn', 'AI', 'Algorithms']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'machine-learning'), (SELECT id FROM public.categories LIMIT 1)),
    'Practical Machine Learning with Python',
    'practical-machine-learning-with-python',
    'Deep Learning, PyTorch, Convolutional Neural Networks, and natural language processing NLP.',
    'Bridge the gap between ML theory and practical production models. Build deep neural networks with PyTorch, image recognition with CNNs, and sentiment classification using transformer language models.',
    'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1600&auto=format&fit=crop&q=80',
    99.99,
    24.99,
    'advanced',
    1920,
    41500,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Machine Learning', 'PyTorch', 'Deep Learning', 'Python', 'Computer Vision']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'artificial-intelligence'), (SELECT id FROM public.categories LIMIT 1)),
    'Artificial Intelligence Fundamentals',
    'artificial-intelligence-fundamentals',
    'Generative AI, Large Language Models (LLMs), Prompt Engineering, and RAG architectures.',
    'Understand modern Artificial Intelligence and how to build applications on top of generative models. Learn prompt engineering, embeddings, vector databases (Pinecone, pgvector), and Retrieval-Augmented Generation (RAG).',
    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1600&auto=format&fit=crop&q=80',
    89.99,
    19.99,
    'all_levels',
    1500,
    89100,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Artificial Intelligence', 'AI', 'LLM', 'Prompt Engineering', 'RAG', 'Generative AI']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'cloud-computing'), (SELECT id FROM public.categories LIMIT 1)),
    'AWS Cloud Practitioner',
    'aws-cloud-practitioner',
    'Pass the AWS Certified Cloud Practitioner (CLF-C02) exam with complete hands-on labs.',
    'Comprehensive preparation course for the AWS Certified Cloud Practitioner exam. Understand cloud computing concepts, AWS global infrastructure, core services (EC2, S3, RDS, Lambda), security, IAM, and billing.',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    84.99,
    16.99,
    'beginner',
    1200,
    92300,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['AWS', 'Cloud Computing', 'Certification', 'DevOps', 'Infrastructure']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'cloud-computing'), (SELECT id FROM public.categories LIMIT 1)),
    'AWS Developer Essentials',
    'aws-developer-essentials',
    'Serverless architectures: AWS Lambda, API Gateway, DynamoDB, SQS, SNS, and CDK infrastructure as code.',
    'Build high-throughput, event-driven serverless backends on AWS. Learn how to write Lambda functions in TypeScript/Node, design DynamoDB single-table schemas, manage asynchronous task queues with SQS, and deploy with AWS CDK.',
    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1600&auto=format&fit=crop&q=80',
    99.99,
    22.99,
    'intermediate',
    1680,
    38100,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['AWS', 'Serverless', 'Lambda', 'DynamoDB', 'Cloud Computing']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'cyber-security'), (SELECT id FROM public.categories LIMIT 1)),
    'Cyber Security Fundamentals',
    'cyber-security-fundamentals',
    'Network defense, vulnerability assessments, public key cryptography, and threat mitigation.',
    'Protect modern networks and digital infrastructures from cyber threats. Learn OSI security layers, port scanning, firewalls, packet analysis with Wireshark, asymmetric cryptography (RSA, ECC), and SOC defense operations.',
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1600&auto=format&fit=crop&q=80',
    89.99,
    19.99,
    'beginner',
    1560,
    58400,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Cyber Security', 'Network Security', 'Cryptography', 'Ethical Hacking']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'cyber-security'), (SELECT id FROM public.categories LIMIT 1)),
    'Ethical Hacking Fundamentals',
    'ethical-hacking-fundamentals',
    'Penetration testing with Kali Linux, Metasploit, web application security (OWASP Top 10).',
    'Learn ethical hacking from a professional penetration tester. Set up a secure lab in VirtualBox with Kali Linux, test web applications for SQL injection and XSS vulnerabilities, exploit buffer overflows, and write executive remediation reports.',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1600&auto=format&fit=crop&q=80',
    109.99,
    24.99,
    'intermediate',
    2160,
    72100,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Cyber Security', 'Ethical Hacking', 'Penetration Testing', 'Kali Linux', 'OWASP']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'ui-ux-design'), (SELECT id FROM public.categories LIMIT 1)),
    'UI/UX Design Masterclass',
    'ui-ux-design-masterclass',
    'User research, wireframing, usability testing, mobile UX design, and conversion rate optimization.',
    'Design software products people love to use. Learn how to conduct user interviews, create personas, design high-converting wireframes, run A/B usability experiments, and apply modern UI aesthetics.',
    'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=1600&auto=format&fit=crop&q=80',
    89.99,
    18.99,
    'all_levels',
    1800,
    78900,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['UI/UX Design', 'Product Design', 'User Research', 'Wireframing', 'Figma']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'ui-ux-design'), (SELECT id FROM public.categories LIMIT 1)),
    'Figma Complete Course',
    'figma-complete-course',
    'Master Auto Layout 5.0, design tokens, component variants, variables, and interactive prototypes.',
    'The definitive Figma masterclass for UI/UX designers. Build a scalable enterprise design system with nested auto layouts, reusable component properties, dark mode color variables, and micro-interaction prototypes.',
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1600&auto=format&fit=crop&q=80',
    79.99,
    14.99,
    'beginner',
    1440,
    64300,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Figma', 'UI/UX Design', 'Design Systems', 'Auto Layout', 'Prototyping']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'mobile-development'), (SELECT id FROM public.categories LIMIT 1)),
    'Flutter Mobile App Development',
    'flutter-mobile-app-development',
    'Build cross-platform iOS and Android apps with Flutter, Dart, Riverpod, and Firebase.',
    'Learn how to build beautiful, natively compiled mobile apps from a single codebase with Google Flutter and Dart. Build full projects: chat applications, e-commerce stores, and Google Maps integration.',
    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1600&auto=format&fit=crop&q=80',
    94.99,
    19.99,
    'all_levels',
    2280,
    51200,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Flutter', 'Mobile Development', 'Dart', 'iOS', 'Android', 'Cross Platform']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'mobile-development'), (SELECT id FROM public.categories LIMIT 1)),
    'Android Development',
    'android-development',
    'Modern Android app development with Kotlin, Jetpack Compose, Coroutines, and Room DB.',
    'Build high-performance native Android apps using official Google best practices. Learn Kotlin, declarative UI with Jetpack Compose, MVVM architecture, Retrofit for REST APIs, and publish to the Google Play Store.',
    'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=1600&auto=format&fit=crop&q=80',
    89.99,
    18.99,
    'intermediate',
    2040,
    43200,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Android', 'Kotlin', 'Jetpack Compose', 'Mobile Development', 'Google Play']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'marketing'), (SELECT id FROM public.categories LIMIT 1)),
    'Digital Marketing Masterclass',
    'digital-marketing-masterclass',
    'SEO, Google Ads, Content Marketing, Email Funnels, and Social Media growth hacking.',
    'Drive real traffic, leads, and sales for any business. Learn how to rank #1 on Google with Search Engine Optimization (SEO), set up profitable Google Search & Display ad campaigns, and build automated email sales funnels.',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&auto=format&fit=crop&q=80',
    79.99,
    14.99,
    'all_levels',
    1560,
    83400,
    4.8,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Digital Marketing', 'Marketing', 'SEO', 'Google Ads', 'Content Marketing']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'marketing'), (SELECT id FROM public.categories LIMIT 1)),
    'Social Media Marketing',
    'social-media-marketing',
    'Instagram, TikTok, LinkedIn, YouTube, and viral content strategies for brands and creators.',
    'Grow a dedicated audience and turn followers into paying customers across Instagram, TikTok, LinkedIn, and YouTube. Learn algorithm optimization, short-form video production, influencer collaborations, and analytics.',
    'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1600&auto=format&fit=crop&q=80',
    69.99,
    14.99,
    'beginner',
    1080,
    47200,
    4.7,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Social Media', 'Marketing', 'Instagram', 'TikTok', 'Branding']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'finance'), (SELECT id FROM public.categories LIMIT 1)),
    'Financial Management',
    'financial-management',
    'Corporate finance, balance sheet analysis, cash flow modeling, budgeting, and capital valuation.',
    'Gain commanding mastery of corporate finance and financial accounting. Learn how to interpret income statements, balance sheets, and cash flow statements, conduct discounted cash flow (DCF) valuation, and manage enterprise budgets.',
    'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1600&auto=format&fit=crop&q=80',
    99.99,
    22.99,
    'intermediate',
    1680,
    39800,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Finance', 'Accounting', 'Financial Modeling', 'Business', 'Valuation']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'business'), (SELECT id FROM public.categories LIMIT 1)),
    'Business Analytics',
    'business-analytics',
    'Data-driven decision making: Tableau dashboards, advanced Excel, power BI, and KPI tracking.',
    'Transform raw business data into actionable executive insights. Master business intelligence tooling: create executive Tableau dashboards, automated Excel reports, customer cohort analysis, and predictive metric forecasts.',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&auto=format&fit=crop&q=80',
    84.99,
    17.99,
    'all_levels',
    1440,
    44100,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Business', 'Analytics', 'Tableau', 'Excel', 'BI', 'Dashboards']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'communication-skills'), (SELECT id FROM public.categories LIMIT 1)),
    'Communication Skills',
    'communication-skills',
    'Executive presence, public speaking, persuasive negotiation, and cross-functional leadership.',
    'Elevate your professional career by mastering persuasive communication. Learn how to present complex technical ideas clearly to executives, resolve team conflicts, lead negotiations, and master active listening.',
    'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1600&auto=format&fit=crop&q=80',
    0,
    0,
    'all_levels',
    600,
    96200,
    4.9,
    'published',
    'free',
    ARRAY[]::TEXT[],
    ARRAY['Communication', 'Leadership', 'Public Speaking', 'Negotiation', 'Free']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'interview-preparation'), (SELECT id FROM public.categories LIMIT 1)),
    'Interview Preparation',
    'interview-preparation',
    'Ace technical coding interviews: Data structures, algorithms, system design, and behavioral questions.',
    'The ultimate tech interview playbook. Master the 75 most common LeetCode patterns (Arrays, Two Pointers, Trees, Graphs, Dynamic Programming), learn scalable system design, and perfect the STAR behavioral interview format.',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1600&auto=format&fit=crop&q=80',
    99.99,
    24.99,
    'intermediate',
    2160,
    81900,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Interview Preparation', 'Algorithms', 'Data Structures', 'System Design', 'Career']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'web-development'), (SELECT id FROM public.categories LIMIT 1)),
    'Git and GitHub',
    'git-and-github',
    'Version control mastery: Branching strategies, rebase, merge conflicts, pull requests, and GitHub Actions.',
    'Never fear merge conflicts again. Master Git from foundational commands (`add`, `commit`, `push`, `pull`) to advanced workflows: interactive rebase, cherry-pick, reflog recovery, pull request code reviews, and automated CI with GitHub Actions.',
    'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=1600&auto=format&fit=crop&q=80',
    0,
    0,
    'all_levels',
    720,
    134000,
    4.9,
    'published',
    'free',
    ARRAY[]::TEXT[],
    ARRAY['Git', 'GitHub', 'DevOps', 'Version Control', 'Collaboration', 'Free']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'cloud-computing'), (SELECT id FROM public.categories LIMIT 1)),
    'Docker and DevOps Fundamentals',
    'docker-and-devops-fundamentals',
    'Containers, Docker Compose, Kubernetes orchestration, CI/CD pipelines, and cloud deployments.',
    'Containerize any application and deploy it with confidence. Learn Dockerfiles, multi-stage builds, Docker Compose for multi-container microservices, Kubernetes pods and deployments, and automated testing pipelines.',
    'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=1600&auto=format&fit=crop&q=80',
    94.99,
    21.99,
    'intermediate',
    1680,
    68400,
    4.9,
    'published',
    'bestseller',
    ARRAY[]::TEXT[],
    ARRAY['Docker', 'DevOps', 'Kubernetes', 'CI/CD', 'Containers', 'Cloud']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'graphic-design'), (SELECT id FROM public.categories LIMIT 1)),
    'Graphic Design Masterclass',
    'graphic-design-masterclass',
    'Photoshop, Illustrator, InDesign, Color Theory, Typography, and Professional Brand Identity Design.',
    'Unleash your creative potential. Learn the core principles of graphic design: color psychology, grid systems, typography pairing, logo creation in Adobe Illustrator, photo retouching in Photoshop, and editorial layout.',
    'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1600&auto=format&fit=crop&q=80',
    79.99,
    16.99,
    'all_levels',
    1560,
    41200,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Graphic Design', 'Photoshop', 'Illustrator', 'Branding', 'Typography']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'photography'), (SELECT id FROM public.categories LIMIT 1)),
    'Digital Photography Masterclass',
    'digital-photography-masterclass',
    'Master your DSLR or Mirrorless camera: Exposure triangle, lighting, composition, and Lightroom.',
    'Take stunning photographs in any environment. Master the exposure triangle (Aperture, Shutter Speed, ISO), natural and studio lighting techniques, creative composition rules, and professional RAW editing in Adobe Lightroom.',
    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1600&auto=format&fit=crop&q=80',
    69.99,
    14.99,
    'beginner',
    1080,
    31400,
    4.8,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Photography', 'Lighting', 'Lightroom', 'Camera', 'Creative']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();

INSERT INTO public.courses (
    instructor_id,
    category_id,
    title,
    slug,
    subtitle,
    description,
    thumbnail_url,
    banner_url,
    price,
    discount_price,
    level,
    duration_minutes,
    student_count,
    average_rating,
    status,
    badge,
    learning_objectives,
    requirements
) VALUES (
    (SELECT id FROM public.teachers LIMIT 1),
    COALESCE((SELECT id FROM public.categories WHERE slug = 'music'), (SELECT id FROM public.categories LIMIT 1)),
    'Music Production with Ableton Live',
    'music-production-with-ableton-live',
    'Beatmaking, sound design, audio synthesis, mixing, and mastering in Ableton Live 12.',
    'Produce broadcast-ready electronic, pop, and hip-hop tracks from scratch. Learn audio synthesis, MIDI programming, audio recording, compression, EQ, reverb spatial design, and final mastering.',
    'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1600&auto=format&fit=crop&q=80',
    89.99,
    19.99,
    'all_levels',
    1440,
    28900,
    4.9,
    'published',
    'trending',
    ARRAY[]::TEXT[],
    ARRAY['Music', 'Ableton Live', 'Audio Production', 'Sound Design', 'Mixing']
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    thumbnail_url = EXCLUDED.thumbnail_url,
    banner_url = EXCLUDED.banner_url,
    price = EXCLUDED.price,
    discount_price = EXCLUDED.discount_price,
    level = EXCLUDED.level,
    duration_minutes = EXCLUDED.duration_minutes,
    student_count = EXCLUDED.student_count,
    average_rating = EXCLUDED.average_rating,
    status = 'published',
    badge = EXCLUDED.badge,
    learning_objectives = EXCLUDED.learning_objectives,
    updated_at = NOW();
